driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[chef-vault]
      - recipe[madalynn::update_chef_client]
      - recipe[madalynn::users]
      - recipe[apt::unattended-upgrades]
      - recipe[madalynn::firewall]
    attributes: {
      'dev_mode': true
    }
  - name: bouncer
    run_list:
      - recipe[chef-vault]
      - recipe[madalynn::update_chef_client]
      - recipe[madalynn::users]
      - recipe[madalynn::sshd]
      - recipe[apt::unattended-upgrades]
    attributes: {
      'dev_mode': true
    }
